# edwm theme: dracula (draculatheme.com palette)
[palette]
bg      = #282A36
fg      = #F8F8F2
bright  = #FFFFFF
accent  = #BD93F9
border  = #44475A
urgent  = #FF5555
muted   = #6272A4

[scheme]
norm    = fg, bg, border
sel     = bg, accent, accent
tagsel  = bg, accent, accent
tasksel = bg, accent, accent
urg     = bg, urgent, urgent
hid     = muted, bg, border
status  = muted, bg, border

dmenu_nb = #282A36
dmenu_nf = #F8F8F2
dmenu_sb = #BD93F9
dmenu_sf = #282A36
