# edwm theme: dracula (draculatheme.com palette)
[palette]
bg      = #282a36
fg      = #f8f8f2
accent  = #6272a4
border  = #44475a
urgent  = #ff5555
muted   = #6272a4
purple  = #bd93f9

[scheme]
norm    = fg, bg, border
sel     = fg, accent, purple
tagsel  = fg, accent, purple
tasksel = fg, accent, purple
urg     = bg, urgent, urgent
hid     = muted, bg, border
status  = fg, bg, border

dmenu_nb = #282a36
dmenu_nf = #f8f8f2
dmenu_sb = #6272a4
dmenu_sf = #f8f8f2
