# edwm theme: tokyo night (github.com/enkia/tokyo-night-vscode-theme)
[palette]
bg      = #1A1B26
fg      = #A9B1D6
bright  = #C0CAF5
accent  = #7AA2F7
border  = #24283B
urgent  = #F7768E
muted   = #565F89

[scheme]
norm    = fg, bg, border
sel     = bg, accent, accent
tagsel  = bg, accent, accent
tasksel = bg, accent, accent
urg     = bg, urgent, urgent
hid     = muted, bg, border
status  = muted, bg, border

dmenu_nb = #1A1B26
dmenu_nf = #A9B1D6
dmenu_sb = #7AA2F7
dmenu_sf = #1A1B26
